apiVersion: apps/v1
kind: Deployment
metadata:
  name: Ayonix AI-MED-deployment
  namespace: AI-MED-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Ayonix-AI-MED
  template:
    metadata:
      labels:
        app: Ayonix-AI-MED
    spec:
      containers:
      - name: Ayonix AI-MED
        image: https://raw.githubusercontent.com/drsadivural/AyonixMedical/main
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
        env:
        - name: AI-MED_API_BASE_URL
          value: "http://ai-med-service.ai-med-namespace.svc.cluster.local:11434/api"
        tty: true
